GET http://127.0.0.1:8000/api/products/ HTTP/1.1

###
POST http://127.0.0.1:8000/api/products/ HTTP/1.1
Content-Type: application/json

{
    "name": "Test Product",
    "price": 19.99,
    "description": "A test product for API testing.",
    "stock": 100
}